openMF/ph-ee-bulk-processor

.github/workflows/test.yml
Passing: https://github.com/afk11/ph-ee-bulk-processor/runs/4844252796?check_suite_focus=true
=> Github Actions workflow to build project

src/main/java/org/mifos/processor/bulk/ConfigurationValidator.java, src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/OrderingRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/SplittingRoute.java, src/main/java/org/mifos/processor/bulk/file/AwsFileTransferImpl.java, src/main/java/org/mifos/processor/bulk/schema/Transaction.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/OrderingWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/SplittingWorker.java, src/main/resources/application.yaml
Contains below updates and implementation
1. Implemented ordering worker.
2. Added `ConfigurationValidator` for validating newly introduced worker-specific configuration.
3. Major code fixes in `splitting-worker`.
=> Implemented ordering logic + minor code fixes

src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java
1. New endpoint `POST:/batchtransactions`
2. API is based on the below specs
```
curl --request POST 'https://bulk-connector.sandbox.fynarfin.io/batchtransactions?type=csv' \
--header 'Platform-TenantId: ibank-usa' \
--header 'X-CorrelationID: 3a4dfab5-0f4f-4e78-b6b5-1aff3859d4e8' \
--header 'filename: ph-ee-bulk-demo-6.csv
--form 'data=@"ph-ee-bulk-demo-6.csv"'
```
=> Batch transactions API updated as per specs

src/main/java/org/mifos/processor/bulk/camel/routes/FileProcessingRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/OrderingRoute.java, src/main/java/org/mifos/processor/bulk/format/helper/GSMAMapper.java, src/main/java/org/mifos/processor/bulk/schema/TestSchema.java, src/main/java/org/mifos/processor/bulk/schema/Transaction.java
1. Updated `Transaction.java` DTO,  as per the latest API spec.
2. Enhanced the data writing back to CSV file using CSVMAPPER to support backward compatibility.
=> Csv update

src/main/java/org/mifos/processor/bulk/camel/routes/BatchStatusRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java, src/main/java/org/mifos/processor/bulk/schema/BatchDTO.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/MergeBackWorker.java
1. Updated `BatchDTO.java` to parse the batch-summary API from operations-app.
2. Updated the logic to support result CSV file.
=> Update the BatchDTO as per the api spec

build.gradle, src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/FileProcessingRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java, src/main/java/org/mifos/processor/bulk/schema/Transaction.java, src/main/java/org/mifos/processor/bulk/schema/TransactionResult.java, src/main/java/org/mifos/processor/bulk/utility/Utils.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/MergeBackWorker.java
1. Added `lambok` dependency.
2. Replaced getters and setters in Transaction and TransactionResult DTOs, now using Lombok annotations.
3. Implemented the handling of the scenario when payment mode is not configured.
4. Now result file will be updated with the proper error message in case of missing payment mode.
=> Updating file status in case of missing payment mode

src/main/java/org/mifos/processor/bulk/HealthCheck.java, src/main/java/org/mifos/processor/bulk/kafka/Consumers.java, src/main/java/org/mifos/processor/bulk/kafka/config/KafkaConsumerConfig.java, src/main/java/org/mifos/processor/bulk/kafka/config/KafkaProducerConfig.java, src/main/java/org/mifos/processor/bulk/kafka/config/KafkaTopicConfig.java, src/main/java/org/mifos/processor/bulk/schema/TransactionOlder.java, src/main/resources/application.yaml
This PR include below changes
1.  Older endpoint support `{{BulkHostName}}/channel/bulk/transfer/{{fileName}}`
2. Kafka setup.
3. Afrimoney payment mode working with GSMA flow.
=> Older endpoint reborn

src/main/java/org/mifos/processor/bulk/camel/routes/FileProcessingRoute.java
* Parsing of double from string fixed in FileProcessingRoute.java
=> Fixes #41 Numperformating fixed for double value

src/main/resources/application.yaml
=> Security fix

build.gradle, src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java, src/main/java/org/mifos/processor/bulk/config/PaymentModeApiMapping.java, src/main/java/org/mifos/processor/bulk/config/PaymentModeConfiguration.java, src/main/resources/application.yaml
* Added api-endpoint configuration for each payment mode.
* Added configuration(dependency) for cucumber test cases.
=> Added configuration for loading endpoint based on payment mode

src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java
* Added the logic for looping in order to start bulk gsma flows
- [X} Add required Swagger annotation and update API documentation with details of any API changes if applicable
@fynmanoj : Please review this. 
@danishjamal104 : for your reference
=> Added loop logic for starting gsma flow

src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java
Refer [PHEE-223](https://fynarfin.atlassian.net/browse/PHEE-223) AND [PHEE-222](https://fynarfin.atlassian.net/browse/PHEE-222)
[PHEE-223]: https://fynarfin.atlassian.net/browse/PHEE-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PHEE-222]: https://fynarfin.atlassian.net/browse/PHEE-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FIXES-223 addresses 222 Updated the external api call headers

src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/resources/application.yaml
Jira link: https://mifosforge.jira.com/browse/GOV-71
Assumptions:
This does not include :
1. Separation of batch summary write and read apis
Includes:
Configurable suggested callback
Updated postman api tests
Related PRs:
https://github.com/openMF/ph-ee-env-template/pull/113
https://github.com/openMF/ph-ee-connector-integration-test/pull/31
=> Suggested Callback Time that is Resolved by Polling

build.gradle
* Describe the changes made and why they were made.
* Add a link to teh design document or include the design bullet points related to this PR here.
=> Upgraded java version

src/main/java/org/mifos/processor/bulk/api/ApiOriginFilter.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/ApprovalWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/BatchStatusWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/FormattingWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/InitSubBatchWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/MergeBackWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/OrderingWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/PartyLookupWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/SendCallbackWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/SplittingWorker.java
- added loggers for bulk processor workers
GOV-262 : https://mifosforge.jira.com/browse/GOV-262?atlOrigin=eyJpIjoiZjliYmU1YTY3YjZkNDIzYmE0NjZiMWZjNDdjNWI2NjkiLCJwIjoiaiJ9
=> Added loggers for workers

src/main/java/org/mifos/processor/bulk/api/ApiOriginFilter.java
- Logged tenant in filters
Jira Ticket GOV- 265 : https://mifosforge.jira.com/browse/GOV-265
=> Added filter for logging tenant

build.gradle, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java, src/main/resources/application.yaml
Contains batch file validations
=> GOV-241: Batch files go through a final check to be clean of defects and inconsistencies

build.gradle
1. Added spring auto dependency management plugin.
2. Added missing `camel-jackson` dependency.
3. Organised and ordered the dependency order.
=> FIX startup issue after the java 17 upgrade

src/main/java/org/mifos/processor/bulk/camel/processor/AccountLookupCallbackProcessor.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/AccountLookupCallbackWorker.java
Publishing Payee DfspId from Account Lookup callback.
=> Publishing Payee DfspId

src/main/java/org/mifos/processor/bulk/api/ApiOriginFilter.java
Jira Ticket : https://mifosforge.jira.com/jira/software/c/projects/GOV/issues/GOV-261?jql=project%20%3D%20%22GOV%22%20AND%20assignee%20%3D%20%2261cd59bef3037f0069bc0572%22%20ORDER%20BY%20created%20DESC
Steps : https://docs.google.com/document/d/1-PgOwUsM77cbpipI81ZRHt4t9gnQ4ryXsEyRSg4m-lM/edit?usp=sharing
- Logging client Ip in bulk processor
@fynmanoj @avikganguly01
=> [GOV-261] Logging client IP

src/main/java/org/mifos/processor/bulk/zeebe/worker/WorkerConfig.java
Fix to fetch property from yaml file correctly.
=> Fix deduplication value fetching from yaml file

src/main/java/org/mifos/processor/bulk/camel/routes/BatchStatusRoute.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/BatchStatusWorker.java
Jira: [PHEE-345](https://fynarfin.atlassian.net/browse/PHEE-345)
[PHEE-345]: https://fynarfin.atlassian.net/browse/PHEE-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PHEE-345: Fix NPE in bulk processor

.circleci/config.yml
- parameterized region for new cluster
Jira Ticket : https://fynarfin.atlassian.net/browse/PHEE-346?atlOrigin=eyJpIjoiY2RhMGRiNzRiYmZhNDcwY2IxMDNmMzhlZWQwYjQ2MjkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
@fynmanoj
=> PHEE-346 Parameterised region

.circleci/config.yml
(https://mifosforge.jira.com/browse/GOV-527)
- Updated CircleCI config yaml to build and push the docker image to docker hub.
-
=> #GOV-527 build and push docker image to Dockerhub

1687948148685_demo.csv, 1687948226649_demo.csv, 1687948321953_demo.csv, src/main/resources/application.yaml
This PR removes merge conflict text (`<<<<<<< HEAD`) and also deletes some unnecessarily generated CSV files.
=> Remove unnecessary merge conflict text from application.yaml

.circleci/config.yml
Add authentication credentials for docker in docker executor in circle-ci config file
=> Add authentication credentials for docker-executor

src/main/java/org/mifos/processor/bulk/HealthCheck.java, src/main/java/org/mifos/processor/bulk/api/ApiOriginFilter.java, src/main/java/org/mifos/processor/bulk/camel/routes/FileRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/HealthRoute.java, src/main/java/org/mifos/processor/bulk/file/AwsFileTransferImpl.java, src/main/java/org/mifos/processor/bulk/file/AzureFileTransferImpl.java, src/main/java/org/mifos/processor/bulk/file/FileTransferService.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeWorkers.java
[PHEE-403 stream batch file instead of saving in byte[]](https://fynarfin.atlassian.net/browse/PHEE-403?atlOrigin=eyJpIjoiNjliNzc5ZjRhZjc3NDI4NGJmNDQ3NTRkMjE5MGRkYzYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-403 stream batch file instead of saving in byte[]

src/main/java/org/mifos/processor/bulk/camel/routes/ExternalApiCallRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/FileRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/file/AwsFileTransferImpl.java, src/main/java/org/mifos/processor/bulk/file/AzureFileTransferImpl.java, src/main/java/org/mifos/processor/bulk/file/FileTransferService.java, src/main/resources/application.yaml
Update in this PR
* Rollback the stream logic for downloading 
* Added paymentMode config in application.yaml
* Added clientCorrelationId header while making externalApiCall
* Removed the duplicate "external-api-cal" route
=> GOV-285 Fixed the regression in bulk

build.gradle
[PHEE-420](https://fynarfin.atlassian.net/browse/PHEE-420)
[PHEE-420]: https://fynarfin.atlassian.net/browse/PHEE-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PHEE-420 Updated the connector-common version

src/main/java/org/mifos/processor/bulk/OperationsAppConfig.java, src/main/java/org/mifos/processor/bulk/camel/routes/BatchAggregateRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/RouteId.java, src/main/java/org/mifos/processor/bulk/kafka/Consumers.java, src/main/java/org/mifos/processor/bulk/schema/BatchDTO.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/AggregateWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/BatchStatusWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/InitSubBatchWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/Worker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/WorkerConfig.java, src/main/resources/application.yaml
[GOV-359](https://mifosforge.jira.com/browse/GOV-359)
[GOV-359]: https://mifosforge.jira.com/browse/GOV-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOV-359: Add batch aggregate worker to bulk processor

src/main/java/org/mifos/processor/bulk/API/definition/BatchTransactions.java, src/main/java/org/mifos/processor/bulk/API/implementation/BatchTransactionsController.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/format/RestRequestConvertor.java, src/main/java/org/mifos/processor/bulk/schema/BatchRequestDTO.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java, src/main/resources/application.yaml
Hot fix for https://github.com/openMF/ph-ee-bulk-processor/pull/119
=> Gov 556 api

src/main/java/org/mifos/processor/bulk/api/CallbackController.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/AuthorizationWorker.java
* Added query param `command=authorize`, while making authorisation call.
=> GOV-325-fix: Fixed the authorisation API call

build.gradle, src/main/java/org/mifos/processor/bulk/zeebe/worker/AuthorizationWorker.java, src/main/resources/application.yaml
* Added a fallback logic to populate the `amount` field in mock payment schema authorization API call.
[PHEE-457](https://fynarfin.atlassian.net/browse/PHEE-457)
[PHEE-457]: https://fynarfin.atlassian.net/browse/PHEE-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PHEE-457 : Fixed the payload while sending auth request to mockpaymentschema

src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/SplittingRoute.java, src/main/java/org/mifos/processor/bulk/schema/SubBatchEntity.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/InitSubBatchWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/SplittingWorker.java
[GOV-360](https://mifosforge.jira.com/browse/GOV-360)
[GOV-360]: https://mifosforge.jira.com/browse/GOV-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOV-360: Enahnced the splitting logic to support subBatch data creation for individual txn

src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/PubSubRoute.java, src/main/java/org/mifos/processor/bulk/config/PubSubConfig.java, src/main/java/org/mifos/processor/bulk/config/SecurityServerConfig.java, src/main/java/org/mifos/processor/bulk/schema/SubscriptionDTO.java, src/main/java/org/mifos/processor/bulk/schema/SubscriptionOptionsDTO.java, src/main/java/org/mifos/processor/bulk/service/SubscriptionService.java, src/main/java/org/mifos/processor/bulk/service/SubscriptionServiceImpl.java, src/main/resources/application.yaml
1. New service which will run on each server startup and create a subscription in SS for receiving updates from requester BB publisher. 
2. Added config for SS.
3. Added config for pub/sub.
[GOV-545](https://mifosforge.jira.com/browse/GOV-545)
[GOV-545]: https://mifosforge.jira.com/browse/GOV-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOV-389 Subscribe to a eventType logic added

src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/DeDuplicationRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/RouteId.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/DeDuplicationWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/OrderingWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/Worker.java
[GOV-325](https://mifosforge.jira.com/browse/GOV-325)
[GOV-325]: https://mifosforge.jira.com/browse/GOV-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOV:325 Implementation of de duplication story

src/main/java/org/mifos/processor/bulk/camel/routes/BaseRouteBuilder.java, src/main/java/org/mifos/processor/bulk/file/config/AwsStorageConfig.java, src/main/resources/application.yaml
[PHEE-494 Add Minio to the ph ee engine helm chart](https://fynarfin.atlassian.net/browse/PHEE-494?atlOrigin=eyJpIjoiZjQ4MjNhZmJmZTdlNDEyZGJhNTAyYzE0MjcyZjkwMWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-494] Add Minio to the ph ee engine helm chart

src/main/resources/application.yaml
[PHEE-515 invalid bulk processor host name in service](https://fynarfin.atlassian.net/browse/PHEE-515?atlOrigin=eyJpIjoiZWQ1ZTZhYWViNTk5NGE0MGE4NTY5OThiNjVjOTQ4ZWMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-515] invalid bulk processor host name in service

src/main/java/org/mifos/processor/bulk/api/definition/BatchTransactions.java, src/main/java/org/mifos/processor/bulk/api/implementation/BatchTransactionsController.java, src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/BatchAggregateRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/SendCallbackRoute.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/AggregateWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/SendCallbackWorker.java, src/main/resources/application.yaml
[PHEE-522 Create Sync callback functionality in bulk](https://fynarfin.atlassian.net/browse/PHEE-522?atlOrigin=eyJpIjoiYjI3ZTM5ZTEwYjk0NDliMmFlNDU0YTI5OTAwYTMzNTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-522] Create Sync callback functionality in bulk

build.gradle, src/main/java/org/mifos/processor/bulk/camel/routes/AccountLookupCallbackRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/AccountLookupRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/RouteId.java, src/main/java/org/mifos/processor/bulk/camel/routes/SplittingRoute.java, src/main/java/org/mifos/processor/bulk/properties/TenantImplementation.java, src/main/java/org/mifos/processor/bulk/properties/TenantImplementationProperties.java, src/main/java/org/mifos/processor/bulk/schema/BatchAccountLookupResponseDTO.java, src/main/java/org/mifos/processor/bulk/schema/BeneficiaryDTO.java, src/main/java/org/mifos/processor/bulk/schema/Transaction.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/AccountLookupWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/BatchAccountLookupCallbackWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/BatchAccountLookupWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/SplittingWorker.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/Worker.java, src/main/resources/application.yaml
[GOV-324](https://mifosforge.jira.com/browse/GOV-324?atlOrigin=eyJpIjoiZGUxMTY4MDY4ZDIzNGYxOGIwMTJmNjQzZWJkM2RjYTQiLCJwIjoiaiJ9)
[GOV-324]: https://mifosforge.jira.com/browse/GOV-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GOV-324] Batch Account Lookup

src/main/java/org/mifos/processor/bulk/camel/routes/SendCallbackRoute.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/BatchAccountLookupWorker.java
[PHEE-522 Create Sync callback functionality in bulk](https://fynarfin.atlassian.net/browse/PHEE-522?atlOrigin=eyJpIjoiYjI3ZTM5ZTEwYjk0NDliMmFlNDU0YTI5OTAwYTMzNTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-522] Create Sync callback functionality in bulk 

src/main/resources/application.yaml
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.
=> [GOV-324]Add colum in yaml file

build.gradle
[PHEE-535 Extract content type boundary logic fix.](https://fynarfin.atlassian.net/browse/PHEE-535?atlOrigin=eyJpIjoiODBhMDc1ZWQ1NTVmNGU5NWJkODAxOGJiMDg3MzM0ZGUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-535] Extract content type boundary logic fix.

build.gradle, src/main/java/org/mifos/processor/bulk/api/definition/AccountLookupApi.java, src/main/java/org/mifos/processor/bulk/camel/routes/AccountLookupRoute.java, src/main/java/org/mifos/processor/bulk/connectors/api/AccountLookupApi.java, src/main/java/org/mifos/processor/bulk/connectors/service/AccountLookupService.java, src/main/java/org/mifos/processor/bulk/connectors/service/RetrofitService.java, src/main/java/org/mifos/processor/bulk/service/BatchAccountLookup.java, src/main/java/org/mifos/processor/bulk/utility/Headers.java
[PHEE-547 Convert batch-account-lookup camel route to Java/Spring in Bulk](https://fynarfin.atlassian.net/browse/PHEE-547?atlOrigin=eyJpIjoiM2JhOWRmNjU2NDc4NGNhNGJkMTM0MGI4MWE2NTc0OTAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-547] Convert batch-account-lookup camel route to Java/Spring

build.gradle, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeClientConfiguration.java, src/main/resources/application.yaml
[PHEE-560 Reduce Memory Consumption of 6 reported services](https://fynarfin.atlassian.net/browse/PHEE-560?atlOrigin=eyJpIjoiZTY2NzcwNWJhMWViNDE0OTk2ODdjNmU0NTliNmRmOTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-560] Reduce Memory Consumption of reported services

src/main/java/org/mifos/processor/bulk/zeebe/worker/AggregateWorker.java, src/main/resources/application.yaml
[PHEE-581 Fix 404 error code issue in aggregate worker](https://fynarfin.atlassian.net/browse/PHEE-581?atlOrigin=eyJpIjoiNTkwZTQxY2IxZWU5NDU5YWEyZGMwMmVhN2FiMDIyZjAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-581] Fixed 404 issue in aggregate worker

src/main/java/org/mifos/processor/bulk/camel/routes/AccountLookupRoute.java, src/main/java/org/mifos/processor/bulk/connectors/service/FileProcessingRouteService.java, src/main/java/org/mifos/processor/bulk/service/FileProcessingRouteService.java
[PHEE-582 FileProcessingRoute to Java/Spring in bulk](https://fynarfin.atlassian.net/browse/PHEE-582?atlOrigin=eyJpIjoiNzk1YzVjYjQ5MDA5NGY4M2IxNTUzZjUxNjMxMjM3NWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-582] FileProcessingRoute to Java/Spring in bulk

src/main/resources/application.yaml
[PHEE-594 fix mojaloop testcases](https://fynarfin.atlassian.net/browse/PHEE-594?atlOrigin=eyJpIjoiMjlkMjBiNGY3NmNlNDk2NGJjY2Q0YWU0ZDBjMDJmOWUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-594] fix mojaloop testcases

src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/connectors/service/ProcessorStartRouteService.java, src/main/resources/application.yaml
[PHEE-586 convert BD-003 camel routes to Java/Spring](https://fynarfin.atlassian.net/browse/PHEE-586?atlOrigin=eyJpIjoiZGE4YzU0NDc1OTk4NDZkZTkwOTE0NTNmNWUwZjQ4MzciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-586] Convert BD-003 camel routes to Java/Spring

src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/connectors/service/ProcessorStartRouteService.java
[PHEE-587 Convert BD-011 routes to Java/Spring](https://fynarfin.atlassian.net/browse/PHEE-587?atlOrigin=eyJpIjoiZjhlZDY5ZjlhZjJlNDIxYmI2ZjExMWRkNDc5NDkwYTMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-587] Convert BD-011 routes to Java/Spring

src/main/java/org/mifos/processor/bulk/camel/routes/SendCallbackRoute.java, src/main/java/org/mifos/processor/bulk/schema/BatchCallbackDTO.java, src/main/java/org/mifos/processor/bulk/zeebe/worker/AggregateWorker.java
[PHEE-615 Create Add batchId and correlationId in batch callback](https://fynarfin.atlassian.net/browse/PHEE-615?atlOrigin=eyJpIjoiY2U4MmJhNjVlMTM4NGQ3ZGE2ODI3Y2ZlYTJkZWM2YmIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-615] Create Add batchId and correlationId in batch callback

src/main/java/org/mifos/processor/bulk/format/RestRequestConvertor.java, src/main/java/org/mifos/processor/bulk/schema/BatchRequestDTO.java
[PHEE-634 batch transaction API request body as per API spec in documentation](https://fynarfin.atlassian.net/browse/PHEE-634?atlOrigin=eyJpIjoiY2EwZTI5ZWU1NTMyNDVlMjhhN2FkN2ZhMGM5NzUwMjkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-634] batch transaction API request body as per API spec in documentation

build.gradle, src/main/resources/application.yaml
(https://mifosforge.jira.com/browse/GOV-134)
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.
=> [GOV-134]  Enable management endpoints for health checks

src/main/java/org/mifos/processor/bulk/api/definition/BatchTransactions.java, src/main/java/org/mifos/processor/bulk/api/implementation/BatchTransactionsController.java, src/main/java/org/mifos/processor/bulk/camel/config/CamelProperties.java, src/main/java/org/mifos/processor/bulk/camel/routes/InitSubBatchRoute.java, src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java, src/main/java/org/mifos/processor/bulk/connectors/service/ProcessorStartRouteService.java, src/main/java/org/mifos/processor/bulk/zeebe/ZeebeVariables.java
Sending payee dfspid variable to closedloop workflow in iniSubBatch
Pending Task - Validating payee dfspId [PHEE-698](https://fynarfin.atlassian.net/browse/PHEE-698)
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.
[PHEE-698]: https://fynarfin.atlassian.net/browse/PHEE-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PHEE-697] Add Payee dfsp id header in batch transaction API
